---
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    container_name: opentelemetry-collector
    ports:
      - 4317:4317
      - 8888:8888
      # - 55678:55678
      # - 55679:55679
    volumes:
      # - /etc/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    restart: unless-stopped
    depends_on:
      - jaeger

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      # - /mnt/c/Users/rcane/Desktop/CODE/OTEL_started_1/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-oss:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      # - /mnt/c/Users/rcane/Desktop/CODE/OTEL_started_1/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
    command: "-config.file=/etc/loki/loki-config.yaml"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    links:
      - loki
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - /mnt/c/Users/rcane/Desktop/CODE/OTEL_started_1/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/log:/var/log
    command: "-config.file=/etc/promtail/promtail-config.yaml"
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "14250:14250" # gRPC port for spans
    environment:
      - COLLECTOR_OTLP_ENABLED=true

